import type { WineRecord } from "./types";

/** Исходная коллекция: используется для сида БД и как запасной вариант, если БД недоступна. */
export const seedWines: WineRecord[] = [
  {
    slug: "rkatsiteli-mtsvane-2024",
    name: "Ркацители–Мцване",
    vintage: 2024,
    color: "WHITE",
    sweetness: "DRY",
    appellation: "ЗГУ «Кубань»",
    intro: "Современное прочтение двух классических грузинских сортов — легкое, яркое и солнечное.",
    origin: "Россия, Краснодарский край",
    grapes: "Мцване, Ркацители",
    aging: null,
    abv: "12–12,5%",
    serving: "10–12 °C",
    appearance: "золотисто-соломенный",
    aroma: "желтое спелое яблоко, легкие цветочные ноты, оттенки сладкой ваты.",
    taste: "округлый, гармоничный, с мягкой фруктовой сладостью, аккуратной кислотностью и ненавязчивыми цитрусовыми нюансами.",
    pairing: "рыба, птица, белое мясо, сыры, морепродукты, овощи и блюда грузинской кухни.",
    imageMain: "/images/wine-rkatsiteli.jpg",
    imageDetail: "/images/wine-rkatsiteli-detail.jpg",
    purchaseUrl: "https://vinotheque.ru/catalog/vino/beloe/vino_rkatsiteli_mtsvane_pozovite_somele_2024_0_75_l/",
    published: true,
    sortOrder: 10,
  },
  {
    slug: "sibirkovy-pinot-gris-2024",
    name: "Сибирьковый–Пино Гри",
    vintage: 2024,
    color: "WHITE",
    sweetness: "DRY",
    appellation: "ЗГУ «Кубань»",
    intro: "Свежий купаж двух сортов, созданный для легкости и чистого, минерального вкуса.",
    origin: "Россия, Краснодарский край",
    grapes: "Сибирьковый, Пино Гри",
    aging: "6 месяцев",
    abv: "11%",
    serving: "8–10 °C",
    appearance: "бледно-соломенный, с легким зеленоватым оттенком",
    aroma: "цитрус, зеленое яблоко и тонкие цветочные ноты.",
    taste: "легкий, освежающий, с яркой кислотностью, грушевыми оттенками и минеральным послевкусием.",
    pairing: "морепродукты, белая рыба, легкая птица, мягкие и свежие сыры.",
    imageMain: "/images/wine-sibirkovy.jpg",
    imageDetail: "/images/wine-sibirkovy-detail.jpg",
    purchaseUrl: "https://vinotheque.ru/catalog/vino/beloe/vino_sibirkovyy_pino_gri_pozovite_somele_2024_0_75_l/",
    published: true,
    sortOrder: 20,
  },
  {
    slug: "cabernet-franc-2024",
    name: "Каберне Фран",
    vintage: 2024,
    color: "RED",
    sweetness: "DRY",
    appellation: "ЗГУ «Кубань. Долина реки Афипс»",
    intro: "Стильное и насыщенное красное вино с ярким сортовым характером.",
    origin: "Россия, Краснодарский край",
    grapes: "Каберне Фран",
    aging: "5 месяцев",
    abv: "13%",
    serving: "16–18 °C",
    appearance: "темно-гранатовый с рубиновыми отблесками",
    aroma: "черная смородина, ежевика, вишня, черный перец и пряные специи.",
    taste: "структурный, насыщенный, с тонами вишни, сливового джема, пряностей и зрелых танинов.",
    pairing: "тушеное и жареное мясо, выдержанные сыры, мясные закуски.",
    imageMain: "/images/wine-cabernet.jpg",
    imageDetail: "/images/wine-cabernet-detail.jpg",
    purchaseUrl: "https://vinotheque.ru/catalog/vino/krasnoe/vino_kaberne_fran_pozovite_somele_2024_0_75_l/",
    published: true,
    sortOrder: 30,
  },
  {
    slug: "cabernet-franc-2023",
    name: "Каберне Фран",
    vintage: 2023,
    color: "RED",
    sweetness: "SEMI_DRY",
    appellation: "ЗГУ «Кубань»",
    intro: "Мягкое, фруктовое и дружелюбное красное, созданное для тех, кто любит яркую ягоду и комфортный стиль.",
    origin: "Россия, Краснодарский край",
    grapes: "Каберне Фран, Каберне Совиньон",
    aging: "5 месяцев",
    abv: "14%",
    serving: "16–18 °C",
    appearance: "темно-гранатовый",
    aroma: "красные и черные ягоды — земляника, малина, ежевика, смородина — с травянистыми и сливочными нюансами.",
    taste: "сбалансированный, мягкий, с округлыми танинами и сочным фруктово-ягодным характером.",
    pairing: "мясные блюда, сыры, закуски, блюда на гриле.",
    imageMain: "/images/wine-cabernet.jpg",
    imageDetail: "/images/wine-cabernet-2023-detail.jpg",
    purchaseUrl: "https://vinotheque.ru/catalog/vino/krasnoe/vino_kaberne_fran_pozovite_somele_2023_0_75_l/",
    published: true,
    sortOrder: 40,
  },
  {
    slug: "kachich-2024",
    name: "Качич",
    vintage: 2024,
    color: "RED",
    sweetness: "DRY",
    appellation: "ЗГУ «Кубань. Долина реки Афипс»",
    intro: "Редкий сорт абхазского происхождения, выращенный на Кубани. Вино мощное, глубокое и характерное.",
    origin: "Россия, Краснодарский край",
    grapes: "Саперави (Качич)",
    aging: "5 месяцев",
    abv: "15%",
    serving: "16–18 °C",
    appearance: "насыщенный красный, с фиолетовыми и рубиновыми бликами",
    aroma: "черная смородина, фиалка, сливочные тона.",
    taste: "плотный, сочный, с приятной терпкостью и длинным, раскрывающимся послевкусием.",
    pairing: "свинина, паста, пицца, мясные закуски, блюда для пикника.",
    imageMain: "/images/wine-kachich.jpg",
    imageDetail: "/images/wine-kachich-detail.jpg",
    purchaseUrl: "https://vinotheque.ru/catalog/vino/krasnoe/vino_kachich_pozovite_somele_2024_0_75_l/",
    published: true,
    sortOrder: 50,
  },
];
